import { spawn as nodeSpawn, type SpawnOptions } from "node:child_process";

interface BrowserChild {
  once(event: "error" | "spawn", listener: (...args: unknown[]) => void): this;
  off(event: "error" | "spawn", listener: (...args: unknown[]) => void): this;
  unref?(): void;
}

export type BrowserSpawn = (command: string, args: readonly string[], options: SpawnOptions) => BrowserChild;

export interface OpenBrowserOptions {
  platform?: NodeJS.Platform;
  spawn?: BrowserSpawn;
}

function windowsStartCommand(url: string): string {
  // URLs are generated by the local viewer. Quotes are rejected so cmd.exe receives one opaque argument.
  if (/[\r\n"]/.test(url)) throw new Error("Invalid browser URL.");
  return `start "" "${url}"`;
}

export function openBrowser(url: string, options: OpenBrowserOptions = {}): Promise<boolean> {
  const platform = options.platform ?? process.platform;
  const spawn = options.spawn ?? (nodeSpawn as unknown as BrowserSpawn);
  const command = platform === "win32" ? "cmd.exe" : platform === "darwin" ? "open" : "xdg-open";
  const args = platform === "win32" ? ["/d", "/s", "/c", windowsStartCommand(url)] : [url];

  return new Promise((resolve) => {
    let child: BrowserChild;
    try {
      child = spawn(command, args, { shell: false, stdio: "ignore", windowsHide: true });
    } catch {
      resolve(false);
      return;
    }

    const settle = (result: boolean) => {
      child.off("error", onError);
      child.off("spawn", onSpawn);
      resolve(result);
    };
    const onError = () => settle(false);
    const onSpawn = () => {
      child.unref?.();
      settle(true);
    };
    child.once("error", onError);
    child.once("spawn", onSpawn);
  });
}
